/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TopUpImport } from './routes/top-up'
import { Route as SkillsNewImport } from './routes/skills_.new'
import { Route as SkillsIdImport } from './routes/skills_.$id'
import { Route as PolarToppedImport } from './routes/polar/topped'
import { Route as PolarSubscribedImport } from './routes/polar/subscribed'

// Create/Update Routes

const TopUpRoute = TopUpImport.update({
  id: '/top-up',
  path: '/top-up',
  getParentRoute: () => rootRoute,
} as any)

const SubscribeRoute = SubscribeImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRoute,
} as any)

const SkillsRoute = SkillsImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRoute,
} as any)

const BalanceRoute = BalanceImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => rootRoute,
} as any)

const SplatRoute = SplatImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRoute,
} as any)

const PolarRouteRoute = PolarRouteImport.update({
  id: '/polar',
  path: '/polar',
  getParentRoute: () => rootRoute,
} as any)

const TopUpIdRoute = TopUpIdImport.update({
  id: '/top-up_/$id',
  path: '/top-up/$id',
  getParentRoute: () => rootRoute,
} as any)

const SubscribeIdRoute = SubscribeIdImport.update({
  id: '/subscribe_/$id',
  path: '/subscribe/$id',
  getParentRoute: () => rootRoute,
} as any)

const SkillsNewRoute = SkillsNewImport.update({
  id: '/skills_/new',
  path: '/skills/new',
  getParentRoute: () => rootRoute,
} as any)

const SkillsIdRoute = SkillsIdImport.update({
  id: '/skills_/$id',
  path: '/skills/$id',
  getParentRoute: () => rootRoute,
} as any)

const PolarToppedRoute = PolarToppedImport.update({
  id: '/topped',
  path: '/topped',
  getParentRoute: () => PolarRouteRoute,
} as any)

const PolarSubscribedRoute = PolarSubscribedImport.update({
  id: '/subscribed',
  path: '/subscribed',
  getParentRoute: () => PolarRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/polar': {
      id: '/polar'
      path: '/polar'
      fullPath: '/polar'
      preLoaderRoute: typeof PolarRouteImport
      parentRoute: typeof rootRoute
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatImport
      parentRoute: typeof rootRoute
    }
    '/balance': {
      id: '/balance'
      path: '/balance'
      fullPath: '/balance'
      preLoaderRoute: typeof BalanceImport
      parentRoute: typeof rootRoute
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsImport
      parentRoute: typeof rootRoute
    }
    '/top-up': {
      id: '/top-up'
      path: '/top-up'
      fullPath: '/top-up'
      preLoaderRoute: typeof TopUpImport
      parentRoute: typeof rootRoute
    }
    '/polar/subscribed': {
      id: '/polar/subscribed'
      path: '/subscribed'
      fullPath: '/polar/subscribed'
      preLoaderRoute: typeof PolarSubscribedImport
      parentRoute: typeof PolarRouteImport
    }
    '/polar/topped': {
      id: '/polar/topped'
      path: '/topped'
      fullPath: '/polar/topped'
      preLoaderRoute: typeof PolarToppedImport
      parentRoute: typeof PolarRouteImport
    }
    '/skills_/$id': {
      id: '/skills_/$id'
      path: '/skills/$id'
      fullPath: '/skills/$id'
      preLoaderRoute: typeof SkillsIdImport
      parentRoute: typeof rootRoute
    }
    '/skills_/new': {
      id: '/skills_/new'
      path: '/skills/new'
      fullPath: '/skills/new'
      preLoaderRoute: typeof SkillsNewImport
      parentRoute: typeof rootRoute
    }
    '/subscribe_/$id': {
      id: '/subscribe_/$id'
      path: '/subscribe/$id'
      fullPath: '/subscribe/$id'
      preLoaderRoute: typeof SubscribeIdImport
      parentRoute: typeof rootRoute
    }
    '/top-up_/$id': {
      id: '/top-up_/$id'
      path: '/top-up/$id'
      fullPath: '/top-up/$id'
      preLoaderRoute: typeof TopUpIdImport
}

}


const PolarRouteRouteWithChildren = PolarRouteRoute._addFileChildren(
  PolarRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/polar': typeof PolarRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/balance': typeof BalanceRoute
  '/skills': typeof SkillsRoute
  '/subscribe': typeof SubscribeRoute
  '/top-up': typeof TopUpRoute
  '/polar/subscribed': typeof PolarSubscribedRoute
  '/polar/topped': typeof PolarToppedRoute
  '/skills/$id': typeof SkillsIdRoute
  '/skills/new': typeof SkillsNewRoute
  '/subscribe/$id': typeof SubscribeIdRoute
  '/top-up/$id': typeof TopUpIdRoute
}

export interface FileRoutesByTo {
  '/polar': typeof PolarRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/balance': typeof BalanceRoute
  '/skills': typeof SkillsRoute
  '/subscribe': typeof SubscribeRoute
  '/top-up': typeof TopUpRoute
  '/polar/subscribed': typeof PolarSubscribedRoute
  '/polar/topped': typeof PolarToppedRoute
  '/skills/$id': typeof SkillsIdRoute
  '/skills/new': typeof SkillsNewRoute
  '/subscribe/$id': typeof SubscribeIdRoute
  '/top-up/$id': typeof TopUpIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/polar': typeof PolarRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/balance': typeof BalanceRoute
  '/skills': typeof SkillsRoute
  '/subscribe': typeof SubscribeRoute
  '/top-up': typeof TopUpRoute
  '/polar/subscribed': typeof PolarSubscribedRoute
  '/polar/topped': typeof PolarToppedRoute
  '/skills_/$id': typeof SkillsIdRoute
  '/skills_/new': typeof SkillsNewRoute
  '/subscribe_/$id': typeof SubscribeIdRoute
  '/top-up_/$id': typeof TopUpIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/polar'
    | '/$'
    | '/balance'
    | '/skills'
    | '/subscribe'
    | '/top-up'
    | '/polar/subscribed'
    | '/polar/topped'
    | '/skills/$id'
    | '/skills/new'
    | '/subscribe/$id'
    | '/top-up/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/polar'
    | '/$'
    | '/balance'
    | '/skills'
    | '/subscribe'
    | '/top-up'
    | '/polar/subscribed'
    | '/polar/topped'
    | '/skills/$id'
    | '/skills/new'
    | '/subscribe/$id'
    | '/top-up/$id'
  id:
    | '__root__'
    | '/polar'
    | '/$'
    | '/balance'
    | '/skills'
    | '/subscribe'
    | '/top-up'
    | '/polar/subscribed'
    | '/polar/topped'
    | '/skills_/$id'
    | '/skills_/new'
    | '/subscribe_/$id'
    | '/top-up_/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  PolarRouteRoute: typeof PolarRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  BalanceRoute: typeof BalanceRoute
  SkillsRoute: typeof SkillsRoute
  SubscribeRoute: typeof SubscribeRoute
  TopUpRoute: typeof TopUpRoute
  SkillsIdRoute: typeof SkillsIdRoute
  SkillsNewRoute: typeof SkillsNewRoute
  SubscribeIdRoute: typeof SubscribeIdRoute
  TopUpIdRoute: typeof TopUpIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  PolarRouteRoute: PolarRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  BalanceRoute: BalanceRoute,
  SkillsRoute: SkillsRoute,
  SubscribeRoute: SubscribeRoute,
  TopUpRoute: TopUpRoute,
  SkillsIdRoute: SkillsIdRoute,
  SkillsNewRoute: SkillsNewRoute,
  SubscribeIdRoute: SubscribeIdRoute,
  TopUpIdRoute: TopUpIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/polar",
        "/$",
        "/balance",
        "/skills",
        "/subscribe",
        "/top-up",
        "/skills_/$id",
        "/skills_/new",
        "/subscribe_/$id",
        "/top-up_/$id"
      ]
    },
    "/polar": {
      "filePath": "polar/route.tsx",
      "children": [
        "/polar/subscribed",
        "/polar/topped"
      ]
    },
    "/$": {
      "filePath": "$.tsx"
    },
    "/balance": {
      "filePath": "balance.tsx"
    },
    "/skills": {
      "filePath": "skills.tsx"
    },
    "/subscribe": {
      "filePath": "subscribe.tsx"
    },
    "/top-up": {
      "filePath": "top-up.tsx"
    },
    "/polar/subscribed": {
      "filePath": "polar/subscribed.tsx",
      "parent": "/polar"
    },
    "/polar/topped": {
      "filePath": "polar/topped.tsx",
      "parent": "/polar"
    },
    "/skills_/$id": {
      "filePath": "skills_.$id.tsx"
    },
    "/skills_/new": {
      "filePath": "skills_.new.tsx"
    },
    "/subscribe_/$id": {
      "filePath": "subscribe_.$id.tsx"
    },
    "/top-up_/$id": {
      "filePath": "top-up_.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
