/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TopUpRouteImport } from './routes/top-up'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SplatRouteImport } from './routes/$'
import { Route as PolarRouteRouteImport } from './routes/polar/route'
import { Route as TopUpIdRouteImport } from './routes/top-up_.$id'
import { Route as SkillsNewRouteImport } from './routes/skills_.new'
import { Route as SkillsIdRouteImport } from './routes/skills_.$id'
import { Route as PolarToppedRouteImport } from './routes/polar/topped'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TopUpRoute = TopUpRouteImport.update({
  id: '/top-up',
  path: '/top-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PolarRouteRoute = PolarRouteRouteImport.update({
  id: '/polar',
  path: '/polar',
  getParentRoute: () => rootRouteImport,
} as any)
const TopUpIdRoute = TopUpIdRouteImport.update({
  id: '/top-up_/$id',
  path: '/top-up/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsNewRoute = SkillsNewRouteImport.update({
  id: '/skills_/new',
  path: '/skills/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIdRoute = SkillsIdRouteImport.update({
  id: '/skills_/$id',
  path: '/skills/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PolarToppedRoute = PolarToppedRouteImport.update({
  id: '/topped',
  path: '/topped',
  getParentRoute: () => PolarRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/polar': typeof PolarRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/skills': typeof SkillsRoute
  '/top-up': typeof TopUpRoute
  '/wallet': typeof WalletRoute
  '/polar/topped': typeof PolarToppedRoute
  '/skills/$id': typeof SkillsIdRoute
  '/skills/new': typeof SkillsNewRoute
  '/top-up/$id': typeof TopUpIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/polar': typeof PolarRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/skills': typeof SkillsRoute
  '/top-up': typeof TopUpRoute
  '/wallet': typeof WalletRoute
  '/polar/topped': typeof PolarToppedRoute
  '/skills/$id': typeof SkillsIdRoute
  '/skills/new': typeof SkillsNewRoute
  '/top-up/$id': typeof TopUpIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/polar': typeof PolarRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/skills': typeof SkillsRoute
  '/top-up': typeof TopUpRoute
  '/wallet': typeof WalletRoute
  '/polar/topped': typeof PolarToppedRoute
  '/skills_/$id': typeof SkillsIdRoute
  '/skills_/new': typeof SkillsNewRoute
  '/top-up_/$id': typeof TopUpIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/polar'
    | '/$'
    | '/skills'
    | '/top-up'
    | '/wallet'
    | '/polar/topped'
    | '/skills/$id'
    | '/skills/new'
    | '/top-up/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/polar'
    | '/$'
    | '/skills'
    | '/top-up'
    | '/wallet'
    | '/polar/topped'
    | '/skills/$id'
    | '/skills/new'
    | '/top-up/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/polar'
    | '/$'
    | '/skills'
    | '/top-up'
    | '/wallet'
    | '/polar/topped'
    | '/skills_/$id'
    | '/skills_/new'
    | '/top-up_/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PolarRouteRoute: typeof PolarRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  SkillsRoute: typeof SkillsRoute
  TopUpRoute: typeof TopUpRoute
  WalletRoute: typeof WalletRoute
  SkillsIdRoute: typeof SkillsIdRoute
  SkillsNewRoute: typeof SkillsNewRoute
  TopUpIdRoute: typeof TopUpIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-up': {
      id: '/top-up'
      path: '/top-up'
      fullPath: '/top-up'
      preLoaderRoute: typeof TopUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polar': {
      id: '/polar'
      path: '/polar'
      fullPath: '/polar'
      preLoaderRoute: typeof PolarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-up_/$id': {
      id: '/top-up_/$id'
      path: '/top-up/$id'
      fullPath: '/top-up/$id'
      preLoaderRoute: typeof TopUpIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills_/new': {
      id: '/skills_/new'
      path: '/skills/new'
      fullPath: '/skills/new'
      preLoaderRoute: typeof SkillsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills_/$id': {
      id: '/skills_/$id'
      path: '/skills/$id'
      fullPath: '/skills/$id'
      preLoaderRoute: typeof SkillsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polar/topped': {
      id: '/polar/topped'
      path: '/topped'
      fullPath: '/polar/topped'
      preLoaderRoute: typeof PolarToppedRouteImport
      parentRoute: typeof PolarRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PolarRouteRouteChildren {
  PolarToppedRoute: typeof PolarToppedRoute
}

const PolarRouteRouteChildren: PolarRouteRouteChildren = {
  PolarToppedRoute: PolarToppedRoute,
}

const PolarRouteRouteWithChildren = PolarRouteRoute._addFileChildren(
  PolarRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PolarRouteRoute: PolarRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  SkillsRoute: SkillsRoute,
  TopUpRoute: TopUpRoute,
  WalletRoute: WalletRoute,
  SkillsIdRoute: SkillsIdRoute,
  SkillsNewRoute: SkillsNewRoute,
  TopUpIdRoute: TopUpIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
