import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

export const PROJECT_ROOT = resolve(__dirname, '..');
export const WORKSPACE_FILE = join(PROJECT_ROOT, 'meseeks.code-workspace');
export const WORKSPACE_TEMPLATE_FILE = join(PROJECT_ROOT, '.config', 'meseeks.code-workspace');

const GENERATED_HEADER = `// THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY
// edit .config/meseeks.code-workspace instead
`;

export function buildGeneratedWorkspaceContent(): string {
	//
	const templateContent = readFileSync(WORKSPACE_TEMPLATE_FILE, 'utf8').trimEnd();

	return `${GENERATED_HEADER}${templateContent}\n`;
}

export function readWorkspaceFileContent(): string {
	//
	if (existsSync(WORKSPACE_FILE)) return readFileSync(WORKSPACE_FILE, 'utf8');

	return buildGeneratedWorkspaceContent();
}

export function writeGeneratedWorkspaceFile(): void {
	//
	writeFileSync(WORKSPACE_FILE, buildGeneratedWorkspaceContent());
}
