/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopUpRouteImport } from './routes/top-up'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SchedulesRouteImport } from './routes/schedules'
import { Route as BalanceRouteImport } from './routes/balance'
import { Route as SplatRouteImport } from './routes/$'
import { Route as PolarRouteRouteImport } from './routes/polar/route'
import { Route as TopUpIdRouteImport } from './routes/top-up_.$id'
import { Route as SkillsNewRouteImport } from './routes/skills_.new'
import { Route as SkillsIdRouteImport } from './routes/skills_.$id'
import { Route as ShareIdRouteImport } from './routes/share_.$id'
import { Route as PolarToppedRouteImport } from './routes/polar/topped'
import { Route as PolarSubscribedRouteImport } from './routes/polar/subscribed'
import { Route as ActionIdRouteImport } from './routes/action_.$id'
import { Route as SkillsInnateKeyRouteImport } from './routes/skills_.innate_.$key'

const TopUpRoute = TopUpRouteImport.update({
  id: '/top-up',
  path: '/top-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesRoute = SchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const BalanceRoute = BalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PolarRouteRoute = PolarRouteRouteImport.update({
  id: '/polar',
  path: '/polar',
  getParentRoute: () => rootRouteImport,
} as any)
const TopUpIdRoute = TopUpIdRouteImport.update({
  id: '/top-up_/$id',
  path: '/top-up/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsNewRoute = SkillsNewRouteImport.update({
  id: '/skills_/new',
  path: '/skills/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIdRoute = SkillsIdRouteImport.update({
  id: '/skills_/$id',
  path: '/skills/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareIdRoute = ShareIdRouteImport.update({
  id: '/share_/$id',
  path: '/share/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PolarToppedRoute = PolarToppedRouteImport.update({
  id: '/topped',
  path: '/topped',
  getParentRoute: () => PolarRouteRoute,
} as any)
const PolarSubscribedRoute = PolarSubscribedRouteImport.update({
  id: '/subscribed',
  path: '/subscribed',
  getParentRoute: () => PolarRouteRoute,
} as any)
const ActionIdRoute = ActionIdRouteImport.update({
  id: '/action_/$id',
  path: '/action/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsInnateKeyRoute = SkillsInnateKeyRouteImport.update({
  id: '/skills_/innate_/$key',
  path: '/skills/innate/$key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/polar': typeof PolarRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/balance': typeof BalanceRoute
  '/schedules': typeof SchedulesRoute
  '/skills': typeof SkillsRoute
  '/subscribe': typeof SubscribeRoute
  '/top-up': typeof TopUpRoute
  '/action/$id': typeof ActionIdRoute
  '/polar/subscribed': typeof PolarSubscribedRoute
  '/polar/topped': typeof PolarToppedRoute
  '/share/$id': typeof ShareIdRoute
  '/skills/$id': typeof SkillsIdRoute
  '/skills/new': typeof SkillsNewRoute
  '/top-up/$id': typeof TopUpIdRoute
  '/skills/innate/$key': typeof SkillsInnateKeyRoute
}
export interface FileRoutesByTo {
  '/polar': typeof PolarRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/balance': typeof BalanceRoute
  '/schedules': typeof SchedulesRoute
  '/skills': typeof SkillsRoute
  '/subscribe': typeof SubscribeRoute
  '/top-up': typeof TopUpRoute
  '/action/$id': typeof ActionIdRoute
  '/polar/subscribed': typeof PolarSubscribedRoute
  '/polar/topped': typeof PolarToppedRoute
  '/share/$id': typeof ShareIdRoute
  '/skills/$id': typeof SkillsIdRoute
  '/skills/new': typeof SkillsNewRoute
  '/top-up/$id': typeof TopUpIdRoute
  '/skills/innate/$key': typeof SkillsInnateKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/polar': typeof PolarRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/balance': typeof BalanceRoute
  '/schedules': typeof SchedulesRoute
  '/skills': typeof SkillsRoute
  '/subscribe': typeof SubscribeRoute
  '/top-up': typeof TopUpRoute
  '/action_/$id': typeof ActionIdRoute
  '/polar/subscribed': typeof PolarSubscribedRoute
  '/polar/topped': typeof PolarToppedRoute
  '/share_/$id': typeof ShareIdRoute
  '/skills_/$id': typeof SkillsIdRoute
  '/skills_/new': typeof SkillsNewRoute
  '/top-up_/$id': typeof TopUpIdRoute
  '/skills_/innate_/$key': typeof SkillsInnateKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/polar'
    | '/$'
    | '/balance'
    | '/schedules'
    | '/skills'
    | '/subscribe'
    | '/top-up'
    | '/action/$id'
    | '/polar/subscribed'
    | '/polar/topped'
    | '/share/$id'
    | '/skills/$id'
    | '/skills/new'
    | '/top-up/$id'
    | '/skills/innate/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/polar'
    | '/$'
    | '/balance'
    | '/schedules'
    | '/skills'
    | '/subscribe'
    | '/top-up'
    | '/action/$id'
    | '/polar/subscribed'
    | '/polar/topped'
    | '/share/$id'
    | '/skills/$id'
    | '/skills/new'
    | '/top-up/$id'
    | '/skills/innate/$key'
  id:
    | '__root__'
    | '/polar'
    | '/$'
    | '/balance'
    | '/schedules'
    | '/skills'
    | '/subscribe'
    | '/top-up'
    | '/action_/$id'
    | '/polar/subscribed'
    | '/polar/topped'
    | '/share_/$id'
    | '/skills_/$id'
    | '/skills_/new'
    | '/top-up_/$id'
    | '/skills_/innate_/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PolarRouteRoute: typeof PolarRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  BalanceRoute: typeof BalanceRoute
  SchedulesRoute: typeof SchedulesRoute
  SkillsRoute: typeof SkillsRoute
  SubscribeRoute: typeof SubscribeRoute
  TopUpRoute: typeof TopUpRoute
  ActionIdRoute: typeof ActionIdRoute
  ShareIdRoute: typeof ShareIdRoute
  SkillsIdRoute: typeof SkillsIdRoute
  SkillsNewRoute: typeof SkillsNewRoute
  TopUpIdRoute: typeof TopUpIdRoute
  SkillsInnateKeyRoute: typeof SkillsInnateKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/top-up': {
      id: '/top-up'
      path: '/top-up'
      fullPath: '/top-up'
      preLoaderRoute: typeof TopUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules': {
      id: '/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof SchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balance': {
      id: '/balance'
      path: '/balance'
      fullPath: '/balance'
      preLoaderRoute: typeof BalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polar': {
      id: '/polar'
      path: '/polar'
      fullPath: '/polar'
      preLoaderRoute: typeof PolarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-up_/$id': {
      id: '/top-up_/$id'
      path: '/top-up/$id'
      fullPath: '/top-up/$id'
      preLoaderRoute: typeof TopUpIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills_/new': {
      id: '/skills_/new'
      path: '/skills/new'
      fullPath: '/skills/new'
      preLoaderRoute: typeof SkillsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills_/$id': {
      id: '/skills_/$id'
      path: '/skills/$id'
      fullPath: '/skills/$id'
      preLoaderRoute: typeof SkillsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share_/$id': {
      id: '/share_/$id'
      path: '/share/$id'
      fullPath: '/share/$id'
      preLoaderRoute: typeof ShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polar/topped': {
      id: '/polar/topped'
      path: '/topped'
      fullPath: '/polar/topped'
      preLoaderRoute: typeof PolarToppedRouteImport
      parentRoute: typeof PolarRouteRoute
    }
    '/polar/subscribed': {
      id: '/polar/subscribed'
      path: '/subscribed'
      fullPath: '/polar/subscribed'
      preLoaderRoute: typeof PolarSubscribedRouteImport
      parentRoute: typeof PolarRouteRoute
    }
    '/action_/$id': {
      id: '/action_/$id'
      path: '/action/$id'
      fullPath: '/action/$id'
      preLoaderRoute: typeof ActionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills_/innate_/$key': {
      id: '/skills_/innate_/$key'
      path: '/skills/innate/$key'
      fullPath: '/skills/innate/$key'
      preLoaderRoute: typeof SkillsInnateKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PolarRouteRouteChildren {
  PolarSubscribedRoute: typeof PolarSubscribedRoute
  PolarToppedRoute: typeof PolarToppedRoute
}

const PolarRouteRouteChildren: PolarRouteRouteChildren = {
  PolarSubscribedRoute: PolarSubscribedRoute,
  PolarToppedRoute: PolarToppedRoute,
}

const PolarRouteRouteWithChildren = PolarRouteRoute._addFileChildren(
  PolarRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PolarRouteRoute: PolarRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  BalanceRoute: BalanceRoute,
  SchedulesRoute: SchedulesRoute,
  SkillsRoute: SkillsRoute,
  SubscribeRoute: SubscribeRoute,
  TopUpRoute: TopUpRoute,
  ActionIdRoute: ActionIdRoute,
  ShareIdRoute: ShareIdRoute,
  SkillsIdRoute: SkillsIdRoute,
  SkillsNewRoute: SkillsNewRoute,
  TopUpIdRoute: TopUpIdRoute,
  SkillsInnateKeyRoute: SkillsInnateKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
